name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# One or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Lint and build tasks
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm install
          npm run tasks
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Build tasks'
          git push
